- name: install sedir systemd service
  template: src=../templates/sedir.service.j2 dest=/etc/systemd/system/sedir.service owner=root group=root mode=0644

# The systemd module is not available until ansible 2.2 so doing this way for now
- name: systemctl daemon-reload
  command: systemctl daemon-reload
