---
- name: This is the top-level playbook for backend servers
  hosts: backend_servers
  remote_user: root

- include: mongo-playbook.yml
- include: node-playbook.yml

- hosts: backend_servers 
  tasks:
    - include: ../tasks/download-backend-code.yml
      static: yes
