---

- hosts: frontend_servers
  roles:
    - franklinkim.ufw
  become: yes
  vars:
    ufw_rules:
      - { port: 80, rule: allow }
      - { port: 443, rule: allow }
      - { from_ip: '127.0.0.1/8' }
    ufw_default_forward_policy: DROP
    ufw_logging: full
    ufw_applications:
     - { name: "OpenSSH" }

